name: CI -> Deploy to My website
on:
  push:
    branches: [ main, development ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@master
        with:
          server: arcusgroup.home.pl
          user: hydrotrade@hydrotrade.pl
          password: ${{ secrets.FTP_PASSWORD_PROJEKTYDLASZKOL }}
          local_dir: "./projektydlaszkolwordpress/wp-content/themes/projektydlaszkol"
          delete: "false"
