name: Staging deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: multiple SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD_PROJEKTYDLASZKOL }}
        port: ${{ secrets.FTP_PORT }}
        script: |
          cd /home/hydrotrade/public_html/projektydlaszkolwordpress/wp-content/themes/projektydlaszkol/
          git fetch --all
